version: 1
build:
  binary: loyald
  ldflags:
  - -X main.Env=prod
  - -X main.Version=0.25.1
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: lyl_validator
  coins:
  - 1000000000ulyl
- name: lyl_faucet
  coins:
  - 101000000000ulyl
  - 10000000000uusl
faucet:
  name: lyl_faucet
  coins:
  - 101000000000ulyl
  - 10000000000uusl
  host: :4501
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    bank:
      denom_metadata:
      - base: ulyl
        denom_units:
        - denom: ulyl
          exponent: 0
        - denom: lyl
          exponent: 6
        description: The native staking token of the Loyal Chain
        display: lyl
        name: Lyl
        symbol: LYL
    crisis:
      constant_fee:
        amount: "1000"
        denom: ulyl
    gov:
      deposit_params:
        min_deposit:
        - amount: "100000000"
          denom: ulyl
    mint:
      params:
        mint_denom: ulyl
    staking:
      params:
        bond_denom: ulyl
        unbonding_time: 1814400s
  chain_id: loyal-1
validators:
- name: lyl_validator
  bonded: 1000000000ulyl
  app:
    api:
      address: :1317
    grpc:
      address: :9090
    grpc-web:
      address: :9091
  config:
    p2p:
      laddr: :26656
    rpc:
      laddr: :26657
      pprof_laddr: :6060
  client:
    keyring-backend: file
